project:
  type: website

website:
  image: "rss-white-logo.png"
  favicon: "rss-white-BG.png"
  twitter-card: true
  open-graph: true
  site-url: https://realworlddatascience.net/
  repo-url: https://github.com/realworlddatascience/realworlddatascience.github.io
  repo-actions: [edit, issue]
  google-analytics: "G-1TTWB7YTR6"
  navbar:
    background: light
    logo: "dummylogo.png"
    logo-alt: "dummy logo"
    left:
      - href: index.qmd
        text: "Home"
      - href: contributor-docs/call-for-contributions.qmd
        text: "Call for contributions"
      - href: news-and-views/editors-blog/posts/2022-10-18-meet-the-team/meet-the-team.qmd
        text: "Meet the team"
      - href: news-and-views/index.qmd
    # right:
    #   - href: https://github.com/realworlddatascience
    #     icon: github
    #     aria-label: GitHub
    #   - href: https://twitter.com/rwdatasci
    #     icon: twitter
    #     aria-label: Twitter
    #   - href: https://realworlddatascience.net/news-and-views/index.xml
    #     icon: rss
    #     aria-label: RSS feed

  sidebar: 
    - title: "Call for contributions"
      style: "floating"
      background: "#FFFFFF"
      contents:
        - href: contributor-docs/call-for-contributions.qmd
          text: "**Call for contributions**"
        - contributor-docs/case-studies.qmd
        - contributor-docs/explainers.qmd
        - contributor-docs/exercises.qmd
        - contributor-docs/datasets.qmd
        - contributor-docs/training-guides.qmd
        - contributor-docs/recommender.qmd
        - contributor-docs/datasciencebites.qmd
        - text: "---"
        - contributor-docs/contributor-guidelines.qmd
        - contributor-docs/style-guide.qmd
    - title: "News and views"
      contents: 
        - href: news-and-views/index.qmd
          text: "**In this section**"
        - news-and-views/interviews/index.qmd
        - news-and-views/datasciencebites/index.qmd
        - news-and-views/editors-blog/index.qmd
        - text: "---"
        - href: news-and-views/newsletter/index.qmd
          text: Newsletter

  page-navigation: true

  page-footer:
    background: "#000000"
    left: "Built by the [RSS](https://rss.org.uk/) using [Quarto](https://quarto.org/)" 
    # center:
    right:
      - contact.qmd 
      - href: https://github.com/realworlddatascience
        icon: github
        aria-label: GitHub
      - href: https://twitter.com/rwdatasci
        icon: twitter
        aria-label: Twitter
      - href: https://fosstodon.org/@rwdatasci
        icon: mastodon
        aria-label: Mastodon
      - href: https://www.linkedin.com/showcase/rss-real-world-data-science
        icon: linkedin
        aria-label: LinkedIn

format:
  html:
    theme: [lux, rwds.scss]
    css: styles.css
    toc: true

execute: 
  freeze: auto