project:
  type: website

website:
  title: "Real World Data Science"
  image: "rss-white-logo.png"
  favicon: "rss-white-BG.png"
  twitter-card: true
  open-graph: true
  site-url: https://realworlddatascience.net/
  repo-url: https://github.com/realworlddatascience/realworlddatascience.github.io
  repo-actions: [edit, issue]
  google-analytics: "G-1TTWB7YTR6"
  navbar:
    logo: "rss-white-logo.png"
    logo-alt: "RSS logo"
    left:
      - href: index.qmd
        text: Overview
      - href: contributor-docs/call-for-contributions.qmd
        text: "Call for contributions"
      - href: news-and-views/editors-blog/posts/2022-10-18-meet-the-team/meet-the-team.qmd
        text: "Meet the team"
      - href: news-and-views/index.qmd
    right:
      - href: https://github.com/realworlddatascience
        icon: github
      - href: https://twitter.com/rwdatasci
        icon: twitter
      - href: https://realworlddatascience.net/news-and-views/index.xml
        icon: rss

  sidebar: 
    - title: "Call for contributions"
      style: "floating"
      background: light
      contents:
        - href: contributor-docs/call-for-contributions.qmd
          text: "**Call for contributions**"
        - contributor-docs/case-studies.qmd
        - contributor-docs/explainers.qmd
        - contributor-docs/exercises.qmd
        - contributor-docs/datasets.qmd
        - contributor-docs/training-guides.qmd
        - contributor-docs/recommender.qmd
        - text: "---"
        - contributor-docs/contributor-guidelines.qmd
        - contributor-docs/style-guide.qmd
    - title: "News and views"
      style: "floating"
      background: light
      contents: 
        - href: news-and-views/index.qmd
          text: "**In this section**"
        - news-and-views/editors-blog/index.qmd
        - news-and-views/datasciencebites/index.qmd

  page-navigation: true

  page-footer:
    left: "Built by the [RSS](https://rss.org.uk/) using [Quarto](https://quarto.org/)" 
    center:
      - contact.qmd  
    right: 
      - href: https://github.com/realworlddatascience
        icon: github
      - href: https://twitter.com/rwdatasci
        icon: twitter
      - href: https://fosstodon.org/@rwdatasci
        icon: mastodon
      - href: https://www.linkedin.com/showcase/rss-real-world-data-science
        icon: linkedin

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true